services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"   # Redis port
      - "8001:8001"   # RedisInsight GUI port
    environment:
      REDIS_PASSWORD_FILE: /run/secrets/redis_password # Set a password for Redis
    volumes:
      - redis-data:/data # Persist Redis data
    secrets:
      - redis_password    
    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          memory: 1g
#          cpus: "0.5"
#    networks:
#      - redis-network

volumes:
  redis-data:

secrets:
  redis_password:
    file: ./redis_password.txt

#networks:
#  redis-network:
#    driver: bridge
