services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: world_content
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672" # RabbitMQ management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  redis:
    image: redis/redis-stack:latest
    container_name: redis_stack
    restart: always
    ports:
      - "6379:6379"  # Redis default port
      - "8001:8001"  # Redis Stack UI port
    volumes:
      - redis_data:/data


volumes:
  redis_data:
  postgres_data:
  rabbitmq_data:

#networks:
#  redis-network:
#    driver: bridge
